#!/usr/bin/python
#Program to delete a user account on MOHH on PSP (with NitePr program and with US version only)

#Next Step: add options to increase program efficiency! :)

'''Functions'''

def reverse(string):
    rev = ""
    length = len(string) - 1

    while length >= 0:
        rev += string[length]
        length -= 1

    return rev

def hexdump(letters):
    hexrepr = ''
    rev = reverse(letters)

    for letter in rev:
        hexrepr += hex(ord(letter))[2:]

    return "0x" + hexrepr.upper()

loop = 0
def generate_hex(name):
    global loop
    length = len(name)
    line1 = "0x01217DD8"
    line2 = "0x01217DDC"
    line3 = "0x01217DE0"
    dump = ""

    if length > 12:
        print("The size of the name cannot exceed 12 characters!")
        exit(1)

    if length <= 4:
        if length < 4:
            for i in range(length , 4):
                '''Essayer de cette maniere:
                name += str(hex(0)[2:])
                '''
                name += " "

        if loop > 0:
            dump = str(" " + hexdump(name) + "\n")
        else:
            dump = line1 + str(" " + hexdump(name) + "\n")

    elif length > 4:
        loop += 1

        if length > 4 and length <= 8:
            if length <= 8:
                for i in range(length , 8):
                    name += " "

            dump = line1 + generate_hex(name[0:4])
            dump += line2 + generate_hex(name[4:8])

        elif length > 8 and length <= 12:
            if length <= 12:
                for i in range(length , 12):
                    name += " "

            dump = line1 + generate_hex(name[0:4])
            dump += line2 + generate_hex(name[4:8])
            dump += line3 + generate_hex(name[8:])

    return dump

'''Main code'''

name = raw_input("Name of the account to delete: ")

#We convert the name to an hex dump
dump = generate_hex(name)

#We write the dump into our final ULES.txt file to activate the Cheat
with open("ULES-00558.txt" , "w") as file:
    file.write("#Persona Deleter\n")
    file.write(";Generated by S0bek\n")
    file.write("#Cheat code to delete %s\n" % name)
    file.write(dump)

if not file.closed:
    file.close()

