#!/usr/bin/python
#Program to delete a user account on MOHH on PSP (with NitePr program and with US version of MOHH only)

'''Functions'''

def reverse(string):
    rev = ""
    length = len(string) - 1

    while length >= 0:
        rev += string[length]
        length -= 1

    return rev

def hexdump(letters):
    hexrepr = ''
    rev = reverse(letters)

    for letter in rev:
        hexrepr += hex(ord(letter))[2:]

    return "0x" + hexrepr.upper()

def generate_hex(name):
    length = len(name)
    dump = ""
    line1 = "0x01217DD8"
    line2 = "0x01217DDC"
    line3 = "0x01217DE0"
    line4 = "0x01217DE4"
    line5 = "0x01217DE8"
    line6 = "" '''Same logic'''

    if length < 24:

        if length <= 4:
            if length < 4:
                for i in range(length , 4):
                    '''Try this to convert null characters into null hexa:
                    name += str(hex(0)[2:])
                    '''
                    name += " "

            dump = str(hexdump(name))

        elif length > 4 and length <= 8:
            if length <= 8:
                for i in range(length , 8):
                    name += " "

            line1 += str(" " + hexdump(name[0:4]))
            line2 += str(" " + hexdump(name[4:]))
            dump = "%s\n%s\n" % (line1 , line2)

        elif length > 8 and length <= 12:
            if length <= 12:
                for i in range(length , 12):
                    name += " "

            line1 += str(" " + hexdump(name[0:4]))
            line2 += str(" " + hexdump(name[4:8]))
            line3 += str(" " + hexdump(name[8:]))
            dump = "%s\n%s\n%s\n" % (line1 , line2 , line3)

        #Next lines code here
        ''''''

        #dump = dump.upper()
        return dump

    else:
        return

'''Main code'''

name = raw_input("Name of the account to delete: ")
#name = name.upper()

#We convert the name to an hex dump
dump = generate_hex(name)

#We write the dump into our final ULES.txt file to activate the Cheat
with open("ULES-00558.txt" , "w") as file:
    file.write("#Persona Deleter\n")
    file.write(";Generated by S0bek\n")
    file.write("#Cheat code to delete %s\n" % name)
    file.write(dump)

#file.closed


